import CustomError from '../../misc/error/CustomError';

/**
 * An error for failed OAuthSession requests.
 *
 * @memberOf module:api/auth
 */
class OAuthSessionError extends CustomError {
    /**
     * @param {string} message        - A user-friendly description of the error.
     * @param {string} [type]         - The machine-friendly error type.
     * @param {int}    [statusCode=0] - The status code, if this was generated by a response.
     */
    constructor(message, type, statusCode=0) {
        super(message);

        /**
         * The user-friendly message about the error.
         * @type {string}
         * @example
         *  // "The user credentials were incorrect."
         *  // "You have enabled 2-Factor authentication. Please click your link in the email."
         */
        this.message = message;

        /**
         * The machine-readable error type.
         * @type {string}
         * @example
         *  // "invalid_request"
         *  // "access_denied"
         */
        this.type = type;

        /**
         * The status code, if this was generated by a response.
         * @type {int}
         */
        this.statusCode = statusCode;
    }
}

export default OAuthSessionError;
